spring:
  jpa:
    database: postgresql
    show-sql: off
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bot
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

bot:
  name: Trvl_2021_bot
  token: 1584892841:AAGHaKYWkzuZuRP0NeswiMh_EPTZpY4F91M

